name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  Functional_Test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Single Test
      run: npx cross-env ENV=functional npm run singleTest
    # - name: Run End-To-End Test
    #   run: npx cross-env ENV=functional npm run endToEndTest
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Test-Report
        path: html-report/
        retention-days: 30